AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  pEnvironment:
    Description: "Environment name."
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "test", "prod"]
  GlueJobName:
    Type: String
    Default: TestGlueStackJob
  GlueJobConnectionName:
    Type: String
    Default: TestPostGres
    Description: Provide connection name otherwise default value will be selected
  GlueJobScriptLocation:
    Type: String
    Default: aws-zhidli/GlueScript/Postgres-ETL
    Description: "location of the glue script file, you dont need to append \"s3://\". CloudFormation template will do it."
  GlueJobBookmark:
    Type: String
    Default: False
    Description: "Select option to enable/disable Job bookmark"
    AllowedValues: [true,false]
    ConstraintDescription: must specify True or False.
  GlueSecurityConfig:
    Type: String
    Default: TestSecurityConfig
    Description: "Security configuration for data encryption at rest"

Conditions:
  UseJobBookmark: !Equals [!Ref GlueJobBookmark, False]

Resources:
  GlueJobIAMRoleName:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: !Join [ '-', ["AWSGlue", !Ref GlueJobName, "policy"] ]
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "s3:GetObject"
                Resource: [
                    "Fn::Join": ["", ["arn:aws:s3:::", !Ref GlueJobScriptLocation,"*"] ]
                  ]
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
# The script already exists and is called by this job
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Role: !Ref GlueJobIAMRoleName
      Connections:
        Connections:
          - !Ref GlueJobConnectionName
      Description: Job created with CloudFormation
      GlueVersion: "1.0"
      Command:
        Name: glueetl
        ScriptLocation: !Join [ '', ["s3://", !Ref GlueJobScriptLocation]]
        PythonVersion: "3"
      DefaultArguments:
        "--job-bookmark-option": !If [UseJobBookmark, "job-bookmark-enable", "job-bookmark-disable"]
        "--aws_account_id": !Ref AWS::AccountId
      AllocatedCapacity: 5
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Name: !Ref GlueJobName
      SecurityConfiguration: !Ref GlueSecurityConfig
